# =============================================================================
# WAN DATASET CONFIGURATION - PURE DATASET ONLY
# This file contains ONLY dataset configuration for musubi-tuner
# =============================================================================

# Global dataset settings
[general]
caption_extension = ".txt"
batch_size = 1
enable_bucket = true
bucket_no_upscale = true

# Image dataset configuration
[[datasets]]
resolution = [512, 640]         # [width, height] format
image_directory = "data/input/obisin"
cache_directory = "data/cache/obisin"
num_repeats = 50                # High repeats for small dataset
caption_extension = ".txt"